server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept   #不包括这个微服务名字，即以这个开头的路径是访问不了的
  prefix: /hfbin   #设置统一前缀路径
  ignored-services: "*"  #忽略所有的微服务真实名字
  routes:
    mydept.serviceId: microservicecloud-dept #
    mydept.path: /mydept/**
 
info:
  app.name: hfbin-microcloud
  company.name: www.hfbin.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

