server:
  port: 80

feign:
  hystrix:
    enabled: true


spring:
  application:
    name: microservicecloud-consul-dept
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=hfbin
        healthCheckPath: /actuator/health
        service-name: ${spring.application.name}
        healthCheckInterval: 15s
        #instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        register: true
        instanceId: ${spring.application.name}
